/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bcarsoft.login.view;

import com.bcarsoft.login.model.LoginTable;

/**
 * This is the center of logins accounts saved.
 * @author abelbcarvalho
 */
public class LoginCenter extends javax.swing.JFrame {
    private final LoginTable loginTable = new LoginTable();

    /**
     * Creates new form LoginCenter
     */
    public LoginCenter() {
        initComponents();
        this.tbLogins.setModel(this.getLoginTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLogins = new javax.swing.JTable();
        panData = new javax.swing.JPanel();
        lblTItle = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblComeBack = new javax.swing.JLabel();
        lblSubTItle = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BCarLog - Login Center");
        getContentPane().setLayout(new java.awt.FlowLayout());

        tbLogins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbLogins);

        lblTItle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTItle.setText("BCarLog - Login Center");

        txtSearch.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        lblComeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/come-back-blue.png"))); // NOI18N
        lblComeBack.setToolTipText("Ir para o inicio de BCarLog.");
        lblComeBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComeBackMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblComeBackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblComeBackMouseEntered(evt);
            }
        });

        lblSubTItle.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblSubTItle.setText("Aqui você pode ver todos os seus logins salvos.");

        javax.swing.GroupLayout panDataLayout = new javax.swing.GroupLayout(panData);
        panData.setLayout(panDataLayout);
        panDataLayout.setHorizontalGroup(
            panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblComeBack)
                .addGap(18, 18, 18)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDataLayout.createSequentialGroup()
                        .addComponent(lblSubTItle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panDataLayout.createSequentialGroup()
                        .addComponent(lblTItle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        panDataLayout.setVerticalGroup(
            panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTItle)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblComeBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubTItle)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnNew.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnNew.setText("Novo");

        javax.swing.GroupLayout panMainLayout = new javax.swing.GroupLayout(panMain);
        panMain.setLayout(panMainLayout);
        panMainLayout.setHorizontalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        panMainLayout.setVerticalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNew)
                .addGap(20, 20, 20))
        );

        getContentPane().add(panMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * It change color.
     * @param evt 
     */
    private void lblComeBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComeBackMouseEntered
        // TODO add your handling code here:
        lblComeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/come-back-yellow.png")));
    }//GEN-LAST:event_lblComeBackMouseEntered

    /**
     * It change color.
     * @param evt 
     */
    private void lblComeBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComeBackMouseExited
        // TODO add your handling code here:
        lblComeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/come-back-blue.png")));
    }//GEN-LAST:event_lblComeBackMouseExited

    /**
     * It go back to previous window.
     * @param evt 
     */
    private void lblComeBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComeBackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblComeBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException 
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCenter.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginCenter().setVisible(true);
        });
    }
    
    // getters

    /**
     * This method returns a model to insert into tbLogins.
     * @return LoginTable Instance.
     */
    public LoginTable getLoginTable() {
        return loginTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblComeBack;
    private javax.swing.JLabel lblSubTItle;
    private javax.swing.JLabel lblTItle;
    private javax.swing.JPanel panData;
    private javax.swing.JPanel panMain;
    private javax.swing.JTable tbLogins;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
