/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bcarsoft.account.view;

import com.bcarsoft.account.model.Account;
import com.bcarsoft.struct.mask.PassMask;
import com.bcarsoft.struct.singleton.SingFacade;
import java.util.ArrayList;
import java.util.List;

/**
 * This is the Sing In Application Window.
 * @author abelbcarvalho
 */
public class AccountAccess extends javax.swing.JFrame {
    private List<String> lPass = new ArrayList<>();
    private String password;

    /**
     * Creates new form AccountAccess
     */
    public AccountAccess() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panData = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblRecovery = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        radShow = new javax.swing.JRadioButton();
        panFunction = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        btnSingIn = new javax.swing.JButton();
        btnSingUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BCarLog - Acesse sua Conta");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setText("BCarLog - Acesse sua Conta");

        javax.swing.GroupLayout panTitleLayout = new javax.swing.GroupLayout(panTitle);
        panTitle.setLayout(panTitleLayout);
        panTitleLayout.setHorizontalGroup(
            panTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTitleLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panTitleLayout.setVerticalGroup(
            panTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblUser.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblUser.setText("Nome de Usuário/E-Mail*");

        lblPass.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblPass.setText("Senha*");

        lblRecovery.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblRecovery.setText("Esqueceu sua Senha?");
        lblRecovery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRecovery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecoveryMouseClicked(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });

        radShow.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        radShow.setText("Mostrar");
        radShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radShowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panDataLayout = new javax.swing.GroupLayout(panData);
        panData.setLayout(panDataLayout);
        panDataLayout.setHorizontalGroup(
            panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecovery)
                    .addGroup(panDataLayout.createSequentialGroup()
                        .addComponent(lblPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radShow))
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDataLayout.setVerticalGroup(
            panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(radShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRecovery)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enter.png"))); // NOI18N

        btnSingIn.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnSingIn.setText("Entrar");
        btnSingIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingInActionPerformed(evt);
            }
        });

        btnSingUp.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnSingUp.setText("Cadastrar");
        btnSingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFunctionLayout = new javax.swing.GroupLayout(panFunction);
        panFunction.setLayout(panFunctionLayout);
        panFunctionLayout.setHorizontalGroup(
            panFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFunctionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFunctionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSingUp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSingIn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        panFunctionLayout.setVerticalGroup(
            panFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFunctionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSingUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSingIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panFunction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is for calls screen to update account application password access.
     * @param evt MouseEvent click.
     */
    private void lblRecoveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecoveryMouseClicked
        // TODO add your handling code here:
        // close window
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(false);
        this.getDefaultCloseOperation();
        // open another window
        AccountRecovery recovery = new AccountRecovery();
        recovery.setDefaultCloseOperation(EXIT_ON_CLOSE);
        recovery.setLocationRelativeTo(null);
        recovery.setVisible(true);
    }//GEN-LAST:event_lblRecoveryMouseClicked

    /**
     * This method is for calls screen to sing up to this application with a default account.
     * @param evt ActionEvent - click into button.
     */
    private void btnSingUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingUpActionPerformed
        // TODO add your handling code here:
        // close window
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(false);
        this.getDefaultCloseOperation();
        // open another window
        AccountRegistry register = new AccountRegistry();
        register.setDefaultCloseOperation(EXIT_ON_CLOSE);
        register.setLocationRelativeTo(null);
        register.setVisible(true);
    }//GEN-LAST:event_btnSingUpActionPerformed

    /**
     * This method is for calls screen to sing in to this application with a saved account.
     * @param evt ActionEvent - click into button.
     */
    private void btnSingInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingInActionPerformed
        // TODO add your handling code here:
        Account account = new Account();
        account.setEmailAcc(this.txtUser.getText());
        account.setUserAcc(this.txtUser.getText());
        account.setPassAcc(this.getPassword());
        List<Account> listA = SingFacade.getInstance().findAccount(account);
        if (listA == null || listA.isEmpty() || listA.size() > 1) {
            // checks no success
            javax.swing.JOptionPane.showMessageDialog
                (null, "Usuário/Email e Senha Inválidos.", "Erro Encontrado", 0);
        } else {
            // success
            javax.swing.JOptionPane.showMessageDialog
                (null, "Sucesso ao Entrar em Sua Conta BCarLog.", "Usuário Encontrado", 0);
            // close this window
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);
            this.setVisible(false);
            this.getDefaultCloseOperation();
        }
    }//GEN-LAST:event_btnSingInActionPerformed

    /**
     * This method calls other text field, in this case, the password text field.
     * @param evt ActionEvent - when user push enter.
     */
    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
        this.txtPassActionPerformed(evt);
    }//GEN-LAST:event_txtUserActionPerformed

    /**
     * This method calls sing in button method.
     * @param evt ActionEvent - when user push enter.
     */
    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
        this.btnSingInActionPerformed(evt);
    }//GEN-LAST:event_txtPassActionPerformed

    /**
     * Show or not the password.
     * @param evt MouseEvent - click.
     */
    private void radShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radShowMouseClicked
        // TODO add your handling code here:
        try {
            if (this.txtPass.getText().isEmpty()) return;
            if (this.radShow.isSelected()) {
                this.txtPass.setText(this.getPassword());
            }
            else {
                this.txtPass.setText(this.getlPass().get(2));
            }
        } catch (IndexOutOfBoundsException e) {
            this.insertMaskPass();
        }
    }//GEN-LAST:event_radShowMouseClicked

    /**
     * Inserts mask into this text field of password.
     * @param evt KeyEvent - Released.
     */
    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        // TODO add your handling code here:
        this.insertMaskPass();
    }//GEN-LAST:event_txtPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException 
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountAccess.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AccountAccess().setVisible(true);
        });
    }
    
    // getters and setters

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<String> getlPass() {
        return lPass;
    }
    
    // ˆ getters and setters
    
    /**
     * This method can insert mask into a password, it 
     * is being used because it needs to work better and 
     * economize code, more than one method use it.
     */
    private void insertMaskPass() {
        // list
        this.getlPass().clear();
        this.getlPass().add(this.txtPass.getText());
        this.getlPass().add(this.getPassword());
        this.getlPass().add("*");
        // when all happen
        this.lPass = PassMask.returnPass(this.getlPass());
        this.setPassword(this.getlPass().get(1));
        if (this.radShow.isSelected()) {
            this.txtPass.setText(this.getPassword());
        } else {
            this.txtPass.setText(this.getlPass().get(2));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSingIn;
    private javax.swing.JButton btnSingUp;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRecovery;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panData;
    private javax.swing.JPanel panFunction;
    private javax.swing.JPanel panTitle;
    private javax.swing.JRadioButton radShow;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
