/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bcarsoft.account.view;

import com.bcarsoft.account.model.Account;
import com.bcarsoft.struct.date.Date;
import com.bcarsoft.struct.mask.DateMask;
import com.bcarsoft.struct.mask.MobileMask;
import com.bcarsoft.struct.mask.PassMask;
import com.bcarsoft.struct.singleton.SingFacade;
import com.bcarsoft.struct.utilities.StringUtil;
import java.util.ArrayList;
import java.util.List;

/**
 * This is the Sing Up Application Window.
 * @author abelbcarvalho
 */
public class AccountRegistry extends javax.swing.JFrame {
    private List<String> lPass = new ArrayList<>();
    private String password;

    /**
     * Creates new form AccountRegistry
     */
    public AccountRegistry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panData = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        radShow = new javax.swing.JRadioButton();
        panFuntions = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        btnComeBack = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        btnSingUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BCarLog - Cadastro de Usuário");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setText("BCarLog - Cadastro de Usuário");

        javax.swing.GroupLayout panTitleLayout = new javax.swing.GroupLayout(panTitle);
        panTitle.setLayout(panTitleLayout);
        panTitleLayout.setHorizontalGroup(
            panTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTitleLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitle)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panTitleLayout.setVerticalGroup(
            panTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTitleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblName.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblName.setText("Nome Completo*");

        lblGender.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblGender.setText("Gênero*");

        lblDate.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblDate.setText("Data de Nascimento*");

        lblUser.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblUser.setText("Nome de Usuário*");

        lblEmail.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblEmail.setText("E-Mail* (exemplo@provedor.com)");

        lblPass.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblPass.setText("Senha* (Mín. 6, Máx. 15)");

        lblMobile.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblMobile.setText("N. Celular*");

        txtName.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        cmbGender.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione*", "Feminino", "Masculino", "Não Informar" }));

        txtDate.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtDate.setText("DD/MM/AAAA");
        txtDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtDateMouseReleased(evt);
            }
        });
        txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDateKeyReleased(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        txtPass.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });

        txtMobile.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMobileKeyReleased(evt);
            }
        });

        radShow.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        radShow.setText("Mostrar");
        radShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radShowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panDataLayout = new javax.swing.GroupLayout(panData);
        panData.setLayout(panDataLayout);
        panDataLayout.setHorizontalGroup(
            panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMobile)
                    .addComponent(lblName)
                    .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panDataLayout.createSequentialGroup()
                            .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panDataLayout.createSequentialGroup()
                                    .addComponent(lblGender)
                                    .addGap(90, 90, 90))
                                .addGroup(panDataLayout.createSequentialGroup()
                                    .addComponent(cmbGender, 0, 1, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDate)))
                        .addComponent(lblUser, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDataLayout.createSequentialGroup()
                        .addComponent(lblPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radShow)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDataLayout.setVerticalGroup(
            panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(radShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMobile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N

        btnComeBack.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnComeBack.setText("<-");
        btnComeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComeBackActionPerformed(evt);
            }
        });

        lblMessage.setText("<html><p>Faça seu cadastro e aproveite!</p><br><p>Realização: BCarSoft</p></html>");

        btnSingUp.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnSingUp.setText("Cadastrar");
        btnSingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFuntionsLayout = new javax.swing.GroupLayout(panFuntions);
        panFuntions.setLayout(panFuntionsLayout);
        panFuntionsLayout.setHorizontalGroup(
            panFuntionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFuntionsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFuntionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panFuntionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFuntionsLayout.createSequentialGroup()
                        .addComponent(lblImg)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFuntionsLayout.createSequentialGroup()
                        .addGroup(panFuntionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSingUp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComeBack, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );
        panFuntionsLayout.setVerticalGroup(
            panFuntionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFuntionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg)
                .addGap(32, 32, 32)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComeBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSingUp)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panFuntions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panFuntions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inserts a mask of data into this text field.
     * @param evt KeyEvent.
     */
    private void txtDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyReleased
        // TODO add your handling code here:
        this.txtDate.setText(DateMask.returnDate(this.txtDate.getText()));
    }//GEN-LAST:event_txtDateKeyReleased

    /**
     * This method clear text field of date.
     * @param evt MouseEvent - released.
     */
    private void txtDateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateMouseReleased
        // TODO add your handling code here:
        this.txtDate.setText("");
    }//GEN-LAST:event_txtDateMouseReleased

    /**
     * Inserts a mask of mobile into this text field.
     * @param evt KeyEvent - Released.
     */
    private void txtMobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyReleased
        // TODO add your handling code here:
        this.txtMobile.setText(MobileMask.returnMobile(this.txtMobile.getText()));
    }//GEN-LAST:event_txtMobileKeyReleased

    /**
     * Inserts mask into this text field of password.
     * @param evt KeyEvent - Released.
     */
    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        // TODO add your handling code here:
        this.insertMaskPass();
    }//GEN-LAST:event_txtPassKeyReleased

    /**
     * Show or not the password.
     * @param evt MouseEvent - click.
     */
    private void radShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radShowMouseClicked
        // TODO add your handling code here:
        try {
            if (this.txtPass.getText().isEmpty()) return;
            if (this.radShow.isSelected()) {
                this.txtPass.setText(this.getPassword());
            }
            else {
                this.txtPass.setText(this.getlPass().get(2));
            }
        } catch (IndexOutOfBoundsException e) {
            this.insertMaskPass();
        }
    }//GEN-LAST:event_radShowMouseClicked

    /**
     * This method calls login application window.
     * @param evt 
     */
    private void btnComeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComeBackActionPerformed
        // TODO add your handling code here:
        // close this window
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(false);
        this.getDefaultCloseOperation();
        // call back the new window
        AccountAccess access = new AccountAccess();
        access.setDefaultCloseOperation(EXIT_ON_CLOSE);
        access.setLocationRelativeTo(null);
        access.setVisible(true);
    }//GEN-LAST:event_btnComeBackActionPerformed

    /**
     * This method does the operation of create a new account.
     * @param evt ActionEvent - click.
     */
    private void btnSingUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingUpActionPerformed
        // TODO add your handling code here:
        Account account = new Account();
        try {
            account.setNameAcc(this.txtName.getText());
            account.setGenderAcc(this.cmbGender.getSelectedItem().toString());
            account.setDate(new Date());
            account.getDate().setDay(Integer.parseInt(StringUtil.cutString(this.txtDate.getText(), 0, 2)));
            account.getDate().setMonth(Integer.parseInt(StringUtil.cutString(this.txtDate.getText(), 3, 5)));
            account.getDate().setYear(Integer.parseInt(StringUtil.cutString(this.txtDate.getText(), 6, 10)));
            account.setUserAcc(this.txtUser.getText());
            account.setEmailAcc(this.txtEmail.getText());
            account.setPassAcc(this.getPassword());
            account.setMobileAcc(this.txtMobile.getText());
        } catch (NumberFormatException | IndexOutOfBoundsException e) {
            javax.swing.JOptionPane.showMessageDialog
                (null, "Não foi possível Cadastrar.", "Erro Encontrado", 0);
            return;
        }
        // check success
        if (SingFacade.getInstance().saveAccount(account)) {
            // success
            javax.swing.JOptionPane.showMessageDialog
                (null, "Sucesso ao Cadastrar Usuário", "Usuário Cadastrado", 0);
            // come back to the previous window that was closed
            this.btnComeBackActionPerformed(evt);
        } else {
            // an error was found
            javax.swing.JOptionPane.showMessageDialog
                (null, "Não foi possível Cadastrar.", "Erro Encontrado", 0);
        }
    }//GEN-LAST:event_btnSingUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException 
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountRegistry.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AccountRegistry().setVisible(true);
        });
    }
    
    // getters and setters

    private List<String> getlPass() {
        return lPass;
    }

    private String getPassword() {
        return password;
    }

    private void setPassword(String password) {
        this.password = password;
    }
    
    // ˆ getters and setters
    
    /**
     * This method can insert mask into a password, it 
     * is being used because it needs to work better and 
     * economize code, more than one method use it.
     */
    private void insertMaskPass() {
        // list
        this.getlPass().clear();
        this.getlPass().add(this.txtPass.getText());
        this.getlPass().add(this.getPassword());
        this.getlPass().add("*");
        // when all happen
        this.lPass = PassMask.returnPass(this.getlPass());
        this.setPassword(this.getlPass().get(1));
        if (this.radShow.isSelected()) {
            this.txtPass.setText(this.getPassword());
        } else {
            this.txtPass.setText(this.getlPass().get(2));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComeBack;
    private javax.swing.JButton btnSingUp;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panData;
    private javax.swing.JPanel panFuntions;
    private javax.swing.JPanel panTitle;
    private javax.swing.JRadioButton radShow;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
