/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bcarsoft.bcarlog;

import com.bcarsoft.account.model.Account;
import com.bcarsoft.account.view.AccountAccess;
import com.bcarsoft.login.view.LoginCenter;
import com.bcarsoft.pass.view.GeraSenha;
import com.bcarsoft.site.view.SiteCenter;

/**
 * This class is for the home from BCarLogCenter.
 * @author abelbcarvalho
 */
public class BCarLogCenter extends javax.swing.JFrame {
    private Account account = new Account();

    /**
     * Creates new form BCarLogCenter
     */
    public BCarLogCenter() {
        initComponents();
    }
    
    /**
     * New Instance BCarLogCenter Alternative.
     * @param account Account Instance.
     */
    public BCarLogCenter(Account account) {
        this.setAccount(account);
        this.initComponents();
        this.txtUser.setText(this.getAccount().getUserAcc());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panHead = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        txtSubtitle = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        panSide = new javax.swing.JPanel();
        txtBcar2 = new javax.swing.JLabel();
        txtBcar1 = new javax.swing.JLabel();
        panMenu = new javax.swing.JPanel();
        lblSaveLogin = new javax.swing.JLabel();
        lblSaveSites = new javax.swing.JLabel();
        lblPassGenerator = new javax.swing.JLabel();
        txtChosse = new javax.swing.JLabel();
        txtLine = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        minProfile = new javax.swing.JMenuItem();
        minDelete = new javax.swing.JMenuItem();
        minLogOut = new javax.swing.JMenuItem();
        menEdit = new javax.swing.JMenu();
        minEditProfile = new javax.swing.JMenuItem();
        minAccessTutorial = new javax.swing.JMenuItem();
        menTools = new javax.swing.JMenu();
        minInsertLogin = new javax.swing.JMenuItem();
        minInsertPass = new javax.swing.JMenuItem();
        minInsertSite = new javax.swing.JMenuItem();
        menAbout = new javax.swing.JMenu();
        minLicence = new javax.swing.JMenuItem();
        minBcarsoft = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BCarLog Center");
        setResizable(false);

        txtTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtTitle.setText("BCarLog Center - Início");

        txtSubtitle.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtSubtitle.setText("Guarde seus logins e sites favoritos.");

        txtUser.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtUser.setText("Nome de Usuário");

        txtBcar2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        txtBcar2.setText("<html> <p> BCarSoft<br> BCarLog </p> </html>");

        txtBcar1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        txtBcar1.setText("<html> <p> BCarSoft<br> BCarLog </p> </html>");

        javax.swing.GroupLayout panSideLayout = new javax.swing.GroupLayout(panSide);
        panSide.setLayout(panSideLayout);
        panSideLayout.setHorizontalGroup(
            panSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSideLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBcar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBcar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panSideLayout.setVerticalGroup(
            panSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSideLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(txtBcar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(txtBcar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        lblSaveLogin.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblSaveLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select-choose-off.png"))); // NOI18N
        lblSaveLogin.setText("Guarde seus Logins");
        lblSaveLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveLoginMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveLoginMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveLoginMouseEntered(evt);
            }
        });

        lblSaveSites.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblSaveSites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select-choose-off.png"))); // NOI18N
        lblSaveSites.setText("Guarde seus Sites");
        lblSaveSites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveSitesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveSitesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveSitesMouseEntered(evt);
            }
        });

        lblPassGenerator.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblPassGenerator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select-choose-off.png"))); // NOI18N
        lblPassGenerator.setText("Gerador de Senhas");
        lblPassGenerator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPassGeneratorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPassGeneratorMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPassGeneratorMouseEntered(evt);
            }
        });

        txtChosse.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtChosse.setText("Escolha a opção desejada.");

        txtLine.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtLine.setText("__________________________");

        javax.swing.GroupLayout panMenuLayout = new javax.swing.GroupLayout(panMenu);
        panMenu.setLayout(panMenuLayout);
        panMenuLayout.setHorizontalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtChosse)
                    .addComponent(lblPassGenerator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSaveSites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSaveLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        panMenuLayout.setVerticalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtChosse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLine, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSaveLogin)
                .addGap(18, 18, 18)
                .addComponent(lblSaveSites)
                .addGap(18, 18, 18)
                .addComponent(lblPassGenerator)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panHeadLayout = new javax.swing.GroupLayout(panHead);
        panHead.setLayout(panHeadLayout);
        panHeadLayout.setHorizontalGroup(
            panHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panHeadLayout.createSequentialGroup()
                        .addComponent(panMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panHeadLayout.createSequentialGroup()
                        .addComponent(txtSubtitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panHeadLayout.createSequentialGroup()
                        .addComponent(txtTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUser)))
                .addContainerGap())
        );
        panHeadLayout.setVerticalGroup(
            panHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeadLayout.createSequentialGroup()
                .addGroup(panHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panHeadLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(txtTitle))
                    .addGroup(panHeadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtUser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panSide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        menFile.setText("Arquivo");

        minProfile.setText("Ver Perfil");
        menFile.add(minProfile);

        minDelete.setText("Excluir Conta");
        menFile.add(minDelete);

        minLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_MASK));
        minLogOut.setText("Sair");
        minLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minLogOutActionPerformed(evt);
            }
        });
        menFile.add(minLogOut);

        jMenuBar1.add(menFile);

        menEdit.setText("Editar");

        minEditProfile.setText("Editar Perfil");
        menEdit.add(minEditProfile);

        minAccessTutorial.setText("Acessar Tutorial");
        menEdit.add(minAccessTutorial);

        jMenuBar1.add(menEdit);

        menTools.setText("Ferramentas");

        minInsertLogin.setText("Inserir Novo Login");
        minInsertLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minInsertLoginActionPerformed(evt);
            }
        });
        menTools.add(minInsertLogin);

        minInsertPass.setText("Gerador de Senhas");
        minInsertPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minInsertPassActionPerformed(evt);
            }
        });
        menTools.add(minInsertPass);

        minInsertSite.setText("Inserir Novo Site");
        minInsertSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minInsertSiteActionPerformed(evt);
            }
        });
        menTools.add(minInsertSite);

        jMenuBar1.add(menTools);

        menAbout.setText("Sobre");

        minLicence.setText("Licença");
        menAbout.add(minLicence);

        minBcarsoft.setText("BCarSoft");
        menAbout.add(minBcarsoft);

        jMenuBar1.add(menAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method calls Login Center.
     * @param evt MouseEvent click.
     */
    private void lblSaveLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveLoginMouseClicked
        // TODO add your handling code here:
        this.saveLogins();
    }//GEN-LAST:event_lblSaveLoginMouseClicked

    /**
     * Selected item.
     * @param evt MouseEvent mouse entered.
     */
    private void lblSaveLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveLoginMouseEntered
        // TODO add your handling code here:
        this.lblSaveLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select-choose-on.png")));
        this.lblSaveLogin.setFont(new java.awt.Font("Lucida Grande", 1, 18));
    }//GEN-LAST:event_lblSaveLoginMouseEntered

    /**
     * No selected item.
     * @param evt MouseEvent mouse exited.
     */
    private void lblSaveLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveLoginMouseExited
        // TODO add your handling code here:
        this.lblSaveLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select-choose-off.png")));
        this.lblSaveLogin.setFont(new java.awt.Font("Lucida Grande", 0, 18));
    }//GEN-LAST:event_lblSaveLoginMouseExited

    /**
     * This method calls Site Center.
     * @param evt MouseEvent - click.
     */
    private void lblSaveSitesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveSitesMouseClicked
        // TODO add your handling code here:
        this.saveSites();
    }//GEN-LAST:event_lblSaveSitesMouseClicked

    /**
     * Selected item.
     * @param evt MouseEvent mouse entered.
     */
    private void lblSaveSitesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveSitesMouseEntered
        // TODO add your handling code here:
        this.lblSaveSites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select-choose-on.png")));
        this.lblSaveSites.setFont(new java.awt.Font("Lucida Grande", 1, 18));
    }//GEN-LAST:event_lblSaveSitesMouseEntered

    /**
     * No selected item.
     * @param evt MouseEvent mouse exited.
     */
    private void lblSaveSitesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveSitesMouseExited
        // TODO add your handling code here:
        this.lblSaveSites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select-choose-off.png")));
        this.lblSaveSites.setFont(new java.awt.Font("Lucida Grande", 0, 18));
    }//GEN-LAST:event_lblSaveSitesMouseExited

    /**
     * This method calls the password generator Class.
     * @param evt MouseEvent click.
     */
    private void lblPassGeneratorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassGeneratorMouseClicked
        // TODO add your handling code here:
        this.generatePass();
    }//GEN-LAST:event_lblPassGeneratorMouseClicked

    /**
     * Selected item.
     * @param evt MouseEvent mouse entered.
     */
    private void lblPassGeneratorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassGeneratorMouseEntered
        // TODO add your handling code here:
        this.lblPassGenerator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select-choose-on.png")));
        this.lblPassGenerator.setFont(new java.awt.Font("Lucida Grande", 1, 18));
    }//GEN-LAST:event_lblPassGeneratorMouseEntered

    /**
     * No selected item.
     * @param evt MouseEvent mouse exited.
     */
    private void lblPassGeneratorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassGeneratorMouseExited
        // TODO add your handling code here:
        this.lblPassGenerator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select-choose-off.png")));
        this.lblPassGenerator.setFont(new java.awt.Font("Lucida Grande", 0, 18));
    }//GEN-LAST:event_lblPassGeneratorMouseExited

    /**
     * Log Out Option Menu.
     * @param evt ActionEvent.
     */
    private void minLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minLogOutActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setAccount(null);
        this.setVisible(false);
        this.getDefaultCloseOperation();
        // calls window of login
        AccountAccess access = new AccountAccess();
        access.setLocationRelativeTo(null);
        access.setDefaultCloseOperation(EXIT_ON_CLOSE);
        access.setVisible(true);
    }//GEN-LAST:event_minLogOutActionPerformed

    /**
     * Login Center Calls.
     * @param evt ActionEvent.
     */
    private void minInsertLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minInsertLoginActionPerformed
        // TODO add your handling code here:
        this.saveLogins();
    }//GEN-LAST:event_minInsertLoginActionPerformed

    /**
     * Site Center Calls.
     * @param evt ActionEvent.
     */
    private void minInsertSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minInsertSiteActionPerformed
        // TODO add your handling code here:
        this.saveSites();
    }//GEN-LAST:event_minInsertSiteActionPerformed

    /**
     * Generate Password Screen Calls.
     * @param evt ActionEvent.
     */
    private void minInsertPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minInsertPassActionPerformed
        // TODO add your handling code here:
        this.generatePass();
    }//GEN-LAST:event_minInsertPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException 
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BCarLogCenter.class.getName()).log(java.util
                    .logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BCarLogCenter().setVisible(true);
        });
    }
    
    /**
     * Save Sites.
     */
    private void saveSites() {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(false);
        this.getDefaultCloseOperation();
        // set data
        SiteCenter site = new SiteCenter(this.getAccount());
        site.setDefaultCloseOperation(EXIT_ON_CLOSE);
        site.setLocationRelativeTo(null);
        site.setVisible(true);
    }
    
    /**
     * Save Logins. 
     */
    private void saveLogins() {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(false);
        this.getDefaultCloseOperation();
        // set data
        LoginCenter login = new LoginCenter(this.getAccount());
        login.setDefaultCloseOperation(EXIT_ON_CLOSE);
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }
    
    /**
     * Generate a new Password.
     */
    private void generatePass() {
        GeraSenha pass = new GeraSenha();
        pass.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pass.setLocationRelativeTo(null);
        pass.setVisible(true);
    }
    
    // getters and setters
    
    private Account getAccount() {
        return account;
    }

    private void setAccount(Account account) {
        this.account = account;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblPassGenerator;
    private javax.swing.JLabel lblSaveLogin;
    private javax.swing.JLabel lblSaveSites;
    private javax.swing.JMenu menAbout;
    private javax.swing.JMenu menEdit;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menTools;
    private javax.swing.JMenuItem minAccessTutorial;
    private javax.swing.JMenuItem minBcarsoft;
    private javax.swing.JMenuItem minDelete;
    private javax.swing.JMenuItem minEditProfile;
    private javax.swing.JMenuItem minInsertLogin;
    private javax.swing.JMenuItem minInsertPass;
    private javax.swing.JMenuItem minInsertSite;
    private javax.swing.JMenuItem minLicence;
    private javax.swing.JMenuItem minLogOut;
    private javax.swing.JMenuItem minProfile;
    private javax.swing.JPanel panHead;
    private javax.swing.JPanel panMenu;
    private javax.swing.JPanel panSide;
    private javax.swing.JLabel txtBcar1;
    private javax.swing.JLabel txtBcar2;
    private javax.swing.JLabel txtChosse;
    private javax.swing.JLabel txtLine;
    private javax.swing.JLabel txtSubtitle;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
