/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bcarsoft.bcarlog;

import com.bcarsoft.account.model.Account;
import com.bcarsoft.struct.mask.PassMask;
import java.util.ArrayList;
import java.util.List;

/**
 * This is the profile screen.
 * @author abelbcarvalho
 */
public class Profile extends javax.swing.JFrame {
    private Account account = new Account();
    private List<String> lPass = new ArrayList<>();

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }
    
    /**
     * New Instance of Profile - Alternative.
     * @param account Account Instance.
     */
    public Profile(Account account) {
        this.setAccount(account);
        this.initComponents();
        // full name
        this.txtFullName.setText(this.getAccount().getNameAcc());
        this.txtFullName.setEditable(false);
        // gender
        this.txtGender.setText(this.getAccount().getGenderAcc());
        this.txtGender.setEditable(false);
        // date born
        this.txtDtNas.setText(
            this.getAccount().getDate().getDay()+"/"+
            this.getAccount().getDate().getMonth()+"/"+
            this.getAccount().getDate().getYear()
        );
        this.txtDtNas.setEditable(false);
        // user
        this.txtUser.setText(this.getAccount().getUserAcc());
        this.txtUser.setEditable(false);
        // email
        this.txtEmail.setText(this.getAccount().getEmailAcc());
        this.txtEmail.setEditable(false);
        // pass
        this.txtPass.setText(this.getAccount().getPassAcc());
        // mobile
        this.txtMobile.setText(this.getAccount().getMobileAcc());
        this.txtMobile.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panHead = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblComeBack = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        panData = new javax.swing.JPanel();
        lblFullName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblDtNas = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtDtNas = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        radShow = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil BCarLog");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setText("Perfil BCarLog");

        lblComeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/come-back-blue.png"))); // NOI18N
        lblComeBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComeBackMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblComeBackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblComeBackMouseEntered(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnEdit.setText("Editar");

        javax.swing.GroupLayout panHeadLayout = new javax.swing.GroupLayout(panHead);
        panHead.setLayout(panHeadLayout);
        panHeadLayout.setHorizontalGroup(
            panHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeadLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblComeBack)
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addGap(16, 16, 16))
        );
        panHeadLayout.setVerticalGroup(
            panHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeadLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitle)
                        .addComponent(btnEdit))
                    .addComponent(lblComeBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFullName.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblFullName.setText("Nome Completo");

        lblGender.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblGender.setText("Gênero");

        lblDtNas.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblDtNas.setText("Data de Nasc.");

        lblUser.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblUser.setText("Usuário");

        lblEmail.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblEmail.setText("E-Mail");

        lblPass.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblPass.setText("Senha");

        lblMobile.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblMobile.setText("Celular");

        txtFullName.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        txtGender.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        txtDtNas.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        txtUser.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        txtPass.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        txtMobile.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        radShow.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        radShow.setText("Mostrar");
        radShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radShowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panDataLayout = new javax.swing.GroupLayout(panData);
        panData.setLayout(panDataLayout);
        panDataLayout.setHorizontalGroup(
            panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panDataLayout.createSequentialGroup()
                        .addComponent(lblPass)
                        .addGap(170, 170, 170)
                        .addComponent(radShow))
                    .addComponent(txtMobile)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser)
                    .addComponent(lblMobile, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFullName)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panDataLayout.createSequentialGroup()
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtNas))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panDataLayout.createSequentialGroup()
                        .addComponent(lblGender)
                        .addGap(107, 107, 107)
                        .addComponent(lblDtNas))
                    .addComponent(txtPass)
                    .addComponent(txtEmail))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panDataLayout.setVerticalGroup(
            panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(lblDtNas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDtNas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(radShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMobile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Show password or not.
     * @param evt MouseEvent - click.
     */
    private void radShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radShowMouseClicked
        // TODO add your handling code here:
        try {
            if (this.txtPass.getText().isEmpty()) return;
            if (this.radShow.isSelected()) {
                this.txtPass.setText(this.getAccount().getPassAcc());
            }
            else {
                this.txtPass.setText(this.getlPass().get(2));
            }
        } catch (IndexOutOfBoundsException e) {
            this.insertMaskPass();
        }
    }//GEN-LAST:event_radShowMouseClicked

    /**
     * It go back to previous window.
     * @param evt 
     */
    private void lblComeBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComeBackMouseClicked
        // TODO add your handling code here:
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(false);
        this.getDefaultCloseOperation();
    }//GEN-LAST:event_lblComeBackMouseClicked

    /**
     * Change Image.
     * @param evt 
     */
    private void lblComeBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComeBackMouseEntered
        // TODO add your handling code here:
        this.lblComeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/come-back-yellow.png")));
    }//GEN-LAST:event_lblComeBackMouseEntered

    /**
     * Change Image.
     * @param evt 
     */
    private void lblComeBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComeBackMouseExited
        // TODO add your handling code here:
        this.lblComeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/come-back-blue.png")));
    }//GEN-LAST:event_lblComeBackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException 
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Profile().setVisible(true);
        });
    }
    
    /**
     * This method can insert mask into a password, it 
     * is being used because it needs to work better and 
     * economize code, more than one method use it.
     */
    private void insertMaskPass() {
        // list
        this.getlPass().clear();
        this.getlPass().add(this.txtPass.getText());
        this.getlPass().add(this.getAccount().getPassAcc());
        this.getlPass().add("*");
        // when all happen
        this.lPass = PassMask.returnPass(this.getlPass());
        this.getAccount().setPassAcc(this.getlPass().get(1));
        if (this.radShow.isSelected()) {
            this.txtPass.setText(this.getAccount().getPassAcc());
        } else {
            this.txtPass.setText(this.getlPass().get(2));
        }
    }
    
    // getters and setters

    private Account getAccount() {
        return account;
    }

    private void setAccount(Account account) {
        this.account = account;
    }

    private List<String> getlPass() {
        return lPass;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lblComeBack;
    private javax.swing.JLabel lblDtNas;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panData;
    private javax.swing.JPanel panHead;
    private javax.swing.JRadioButton radShow;
    private javax.swing.JTextField txtDtNas;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
